FROM node:20-alpine AS build
WORKDIR /app

COPY web/package*.json ./web/
RUN cd web && npm ci

COPY web ./web
RUN cd web && npm run build

FROM alpine AS final
WORKDIR /out
COPY --from=build /app/web/dist ./
CMD ["sh", "-c", "cp -r /out/. /var/www/web/ && echo 'Frontend deployed' && tail -f /dev/null"]
