name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/campus-fest-summer
            git pull
            docker compose build
            docker compose up -d
            cp sirius-campus.nginx.conf /etc/nginx/sites-available/sirius-campus.ru
            nginx -t && systemctl reload nginx
